import { useCallback, useEffect, useState } from 'react';
import * as Crypto from 'expo-crypto';

import type { Chat, Message } from './types';
import { loadChats, saveChats } from './storage';

// Placeholder assistant reply. Real replies will come from the claude -p backend,
// which is not connected yet.
const PLACEHOLDER_REPLY =
  "I'm here with you. (Placeholder — Sana's replies will be generated by Claude once the backend is connected.)";

export function useChats() {
  const [chats, setChats] = useState<Chat[]>([]);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    loadChats().then((stored) => {
      setChats(stored);
      setLoaded(true);
    });
  }, []);

  const createChat = useCallback((): Chat => {
    const now = Date.now();
    const chat: Chat = {
      id: Crypto.randomUUID(),
      title: 'New chat',
      messages: [],
      createdAt: now,
      updatedAt: now,
    };
    setChats((prev) => {
      const next = [chat, ...prev];
      void saveChats(next);
      return next;
    });
    return chat;
  }, []);

  const sendMessage = useCallback((chatId: string, content: string) => {
    setChats((prev) => {
      const target = prev.find((c) => c.id === chatId);
      if (!target) return prev;
      const now = Date.now();
      const userMessage: Message = {
        id: Crypto.randomUUID(),
        role: 'user',
        content,
        createdAt: now,
      };
      const assistantMessage: Message = {
        id: Crypto.randomUUID(),
        role: 'assistant',
        content: PLACEHOLDER_REPLY,
        createdAt: now + 1,
      };
      const updated: Chat = {
        ...target,
        messages: [...target.messages, userMessage, assistantMessage],
        title: target.messages.length === 0 ? deriveTitle(content) : target.title,
        updatedAt: now,
      };
      const next = [updated, ...prev.filter((c) => c.id !== chatId)];
      void saveChats(next);
      return next;
    });
  }, []);

  return { chats, loaded, createChat, sendMessage };
}

function deriveTitle(text: string): string {
  const clean = text.trim().replace(/\s+/g, ' ');
  if (!clean) return 'New chat';
  return clean.length > 40 ? `${clean.slice(0, 40)}…` : clean;
}
